config/routes.rb
SampleApp::Application.routes.draw do
  

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  

  
    match '/contact', :to => 'pages#contact'
    match '/about', :to => 'pages#about'
    match '/help', :to => 'pages#help'
    match '/signup', :to => 'users#new'
    
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20100829021049
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean
#

class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :microposts,    :dependent => :destroy
  has_many :relationships, :dependent => :destroy,
                           :foreign_key => "follower_id"
  has_many :reverse_relationships, :dependent => :destroy,
                                   :foreign_key => "followed_id",
                                   :class_name => "Relationship"
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships,
                       :source  => :follower
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end

  class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
  
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
    include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "home"
  end

  def contact
    @title = "contact"
  end

    def about
      @title = "about"
    end
    
    def help
        @title = "help"
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_filter :authenticate, :only => [:index, :edit, :update]
    before_filter :correct_user, :only => [:edit, :update]
  
    def show
        #@user = User.find(params[:id])
        @user = User.find(params[:id])
        @title = @user.name
    end
    
    def index
        @title = "All users"
        @users = User.all
    end
  
    def new
        @user = User.new
        @title = "Sign up"
    end
    
    def create
        @user = User.new(params[:user]) 
        if @user.save
            sign_in @user
            redirect_to @user, :flash => { :success => "Welcome to the Sample App!" }
        else
            @title = "Sign up"
            render 'new'
        end 
    end
    
    def edit
        @title = "Edit user"
    end
    
    def update
        if @user.update_attributes(params[:user])
            redirect_to @user, :flash => { :success => "Profile updated." }
            else
            @title = "Edit user"
            render 'edit'
        end 
    end
    
    
    
    private
    
        def authenticate
            deny_access unless signed_in?
        end
    
        def correct_user # see before_filter
            @user = User.find(params[:id]) 
            redirect_to(root_path) unless current_user?(@user)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Tutorial Sample App" 
    if @title.nil?
        base_title
    else
      "#{base_title} | #{@title}"
    end 
  end
    
    def logo
        image_tag("logo.png", :alt => "Sample App", :class => "round")
    end
  
end

app/helpers/pages_helper.rb
module PagesHelper
  
  
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { :size => 50 }) 
        gravatar_image_tag(user.email.downcase, :alt => user.name,
                                                :class => 'gravatar',
                                                :gravatar => options)
    end
end

app/views/layouts/_footer.html.erb
<footer>
<nav class="round">
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
<li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
</ul> </nav>
</footer>

app/views/layouts/_header.html.erb
	<header>
	<%= logo = image_tag("images/logo.png", :alt => "Sample App", :class => "round") %> 
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li> 
            <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <% end %>
			<li><%= link_to "Help", help_path %></li> 
            <% if signed_in? %>
                <li><%= link_to "Sign out", signout_path, :method => :delete %></li> 
            <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
		</ul> 
	</nav>
	</header>

app/views/layouts/_stylesheets.html.erb
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> 
	<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %> </title>
	<%= csrf_meta_tags %>		
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag "application" %>

</head>
<body>

<div class="container"> 
	<%= render 'layouts/header' %>
	<section class="round">
        <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
        <% end %>
		<%= yield %> 
	</section>
	<%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1> <p>
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1> <p>      Contact Ruby on Rails Tutorial about the sample app at the<a href="http://railstutorial.org/feedback">feedback page</a>. </p>

app/views/pages/help.html.erb
<h1>Sample App</h1> 
<p>
This is the help page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</p> 

app/views/pages/home.html.erb
<h1>Sample App</h1> 
<p>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</p> 

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/index.html.erb
<h1>All users</h1>
<ul class="users">
<% @users.each do |user| %>
<li>
    <%= gravatar_for user, :size => 30 %>
    <%= link_to user.name, user %> 
</li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %> 
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %> 
    </div>
    <div class="field">
        <%= f.label :email %><br /> 
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %> 
    </div>
    <div class="field">
        <%= f.label :password_confirmation, "Confirmation" %><br /> 
        <%=f.password_field :password_confirmation %>
    </div>
    <div class="actions">
        <%= f.submit "Sign up" %> 
    </div>
<% end %>